### ISSUE TITLE
Dica para o próximo livro

### ISSUE THREAD

**Issue by wagnerr92** [FabricaDeSinapse/livro-android-casa-do-codigo#7]
Olá, iniciei a leitura agora e a mesma está me prendendo bastante, livro muito gostoso de se ler. Infelizmente tem um pontomuito chato mesmo que é essa divisão de capítulos no código.  

  É ótimo ter todo o código no git para consulta, mas poderia ter commits separados por branches, pois fica um caos ver vários capítulos no Android Studio, vários builds.gradle. Não sei como o mercado faz para android, mas em web costumamos separar por branches. Ex: quero ver algo do capítulo 2, mudo para a branch do capítulo 2. Acredito que isso facilita e não deixa tanta poluição visual na IDE. 
 
   Eu também gostaria de ir comitando passo a passo o meu desenvolvimento, para depois utilizar como um portfólio no git, mas do jeito que foi estruturado fica um pouco complicado pra mim que não tenho tanta experiência com git.

  Quanto aos demais pontos estou curtindo muito, parabéns pela didática, apenas este ponto de não utilizar branches que frustrou um pouco a minha ideia de ir comitando passo a passo, até tentei abrir só a my-project no Android Studio, mas da erro pois falta algo que está em alguma das outras pastas.

**Comment by paulosalvatore** [comment]
Oi, @wagnerr92, agradeço pela criação da issue.
Demorei um pouquinho para conseguir atender seu pedido e realizar as modificações no projeto.

Fiz a criação e organização das branches, adicionando o [README.md](https://github.com/FabricaDeSinapse/livro-android-casa-do-codigo/blob/main/README.md) com instruções detalhadas sobre a organização do repositório.

Veja se assim fica mais fácil de entender o projeto e de evoluir no desenvolvimento dele.

Um abraço!
